// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const getPasswordByEmail = `-- name: GetPasswordByEmail :one
SELECT Password FROM Users
WHERE Email = $1
`

func (q *Queries) GetPasswordByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordByEmail, email)
	var password string
	err := row.Scan(&password)
	return password, err
}

const registerUser = `-- name: RegisterUser :exec
INSERT INTO Users (UserID, FirstName, LastName, Email, Password)
VALUES ($1, $2, $3, $4, $5)
`

type RegisterUserParams struct {
	Userid    string
	Firstname string
	Lastname  string
	Email     string
	Password  string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.ExecContext(ctx, registerUser,
		arg.Userid,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	return err
}
