// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	Userid     string
	Firstname  string
	Lastname   string
	Email      string
	Isverified sql.NullBool
	Password   string
	Createdat  time.Time
	Updatedat  time.Time
	Deletedat  sql.NullTime
}
